version: '3.8'

services:
  hr-app:
    build: ./hr
    env_file: ./hr/prod.env
    image: hr-app
    command: yarn start
    ports:
      - '3000:3000'
    depends_on:
      - postgresdb2
    volumes:
      - ./hr:/usr/src/hr-app
    networks:
      - node-network

  auth-app:
    build: ./auth
    env_file: ./auth/prod.env
    image: auth-app
    command: yarn start
    ports:
      - '3001:3000'
    depends_on:
      - postgresdb2
    volumes:
      - ./auth:/usr/src/auth-app
    networks:
      - node-network

  postgresdb2:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nodejshr
      - POSTGRES_DB=mydb
    ports:
      - '54323:5432'
    volumes:
      - dbdata2:/var/lib/postgresql/data
    networks:
      - node-network

volumes:
  dbdata2:
    driver: local

networks:
  node-network:
    driver: bridge
