
version: '3.8'
services:
  db-test:
    image: postgres
    restart: always
    container_name: postgresdb-util-test
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nodejshr
      - POSTGRES_DB=test_db

    ports:
      - '54323:5432'
    volumes: 
      - db-test2:/var/lib/postgresql/data
     # Set health checks to wait until postgres has started
    options: >-
      --health-cmd pg_isready
      --health-interval 10s
      --health-timeout 5s
      --health-retries 5
volumes:
  db-test2:
    driver: local
