apiVersion: apps/v1
kind: Deployment
metadata:
     name: postgres-deployment
     namespace: ld-be-hr
spec:
     selector:
          matchLabels:
               app: postgres-app
     replicas: 1
     minReadySeconds: 15
     strategy:
          type: RollingUpdate
          rollingUpdate:
               maxUnavailable: 1
               maxSurge: 1
     template:
          metadata:
               labels:
                    app: postgres-app
          spec:
               containers:
                    - image: postgres
                      imagePullPolicy: Always
                      name: postgres-pod
                      ports:
                           - containerPort: 5432
                      env:
                           - name: POSTGRES_HOST
                             value: postgres-service
                           - name: POSTGRES_PORT
                             value: "5432"
                           - name: POSTGRES_USER
                             value: postgres
                           - name: POSTGRES_PASSWORD
                             value: nodejshr
                           - name: POSTGRES_DB
                             value: mydb
                      volumeMounts:
                           - name: postgres-data
                             mountPath: /var/lib/postgresql/data
                      resources:
                           requests:
                                memory: "256Mi"
                                cpu: "0.5"
                           limits:
                                memory: "512Mi"
                                cpu: "1"
               volumes:
                    - name: postgres-data
                      persistentVolumeClaim:
                           claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
     name: postgres-service
     namespace: ld-be-hr
spec:
     ports:
          - port: 5432
            targetPort: 5432
     selector:
          app: postgres-app

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
     name: postgres-pvc
     namespace: ld-be-hr
spec:
     accessModes:
          - ReadWriteOnce
     resources:
          requests:
               storage: "256Mi"
